server:
  port: 8801

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone} #注册中心地址
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # api文档页面
#    status-page-url: http://localhost:${server.port}/swagger-ui.html # api文档页面
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign: #远程连接
  hystrix: #熔断器配置
    enabled: true #启动熔断器
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #Hystrix\u662F\u5426\u542F\u7528\u8D85\u65F6\u65F6\u95F4
        isolation:
          thread:
            timeoutInMilliseconds: 8000 #Hystrix\u65AD\u8DEF\u5668\u7684\u8D85\u65F6\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u662F1s\uFF0C\u65AD\u8DEF\u5668\u7684\u8D85\u65F6\u65F6\u95F4\u9700\u8981\u5927\u4E8Eribbon\u7684\u8D85\u65F6\u65F6\u95F4\uFF0C\u4E0D\u7136\u4E0D\u4F1A\u89E6\u53D1\u91CD\u8BD5
          strategy: SEMAPHORE
spring:
  rabbitmq:
    host: ${config.mq.host} #rabbitMQ服务器地址
    port: ${config.mq.port}  #rabbitMQ服务器端口
    username: ${config.mq.username}
    password: ${config.mq.password}
    virtual-host: ${config.mq.virtual-host}
#测试
words: 7777